path: ../TS_yolo/dataset_1/glare/bins_80_clip_8_times4/
train: train/images/ # train images (relative to 'path') 128 images
val: val/images/ # val images (relative to 'path') 128 images

names:
    0: car