path: ../TS_yolo/dataset_1/glare/seq_20_delay_30_clip_16/
train: train/images/ # train images (relative to 'path') 128 images
val: val/images/ # val images (relative to 'path') 128 images

names:
    0: car